name: Deploy Recipe Browser

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout github action"
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          VERBOSE: false
          INITIAL_VERSION: 0.1.0

      - name: Remove Leading v From Version Number
        shell: bash
        run: |
          # Retreive Version Number from previous job, and remove the leading v from it
          # v1.2.3 => 1.2.3
          # Add to environment variable for future use
          version=$(echo "${{ steps.bump-version.outputs.tag}}" | sed "s/^v//")
          echo "VERSION=${version}" >> $GITHUB_ENV

      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - run: yarn install

      - name: Set Yarn Version Number 
        shell: bash
        run:
          yarn version --no-git-tag-version --new-version "${{env.VERSION}}"

      - run: yarn run build
        env:
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}
          SEARCH_SERVICE: ${{ secrets.SEARCH_SERVICE }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Upload S3
        run: |
            aws s3 sync dist/ s3://ci.sagebrushgis.com/

      - name: Invalidate Cache
        run: |
            aws cloudfront create-invalidation --distribution-id E35686XIUW6DBM --paths /index.html 